version: "3.9"
services:
  minio:
    command: server /data --console-address ":9001"
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
  redpanda:
    command:
      - redpanda
      - start
      - --smp
      - "1"
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - "0"
    image: docker.vectorized.io/vectorized/redpanda:v22.3.9
    ports:
      - 9092:9092
