on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19.4]
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3
    - run: make test
